language: dart
sudo: false
dart:
  - stable
  - dev
install:
  - gem install coveralls-lcov
script:
  - ./tools/travis.sh
after_success:
  - (coveralls-lcov coverage/lcov.info)
cache:
  directories:
    - $HOME/.pub-cache
