name: process
version: 1.0.0
authors:
- Todd Volkert <tvolkert@google.com>
description: A pluggable, mockable process invocation abstraction for Dart.
homepage: https://github.com/tvolkert/process

dependencies:
  meta: ^1.0.4
  file: ^1.0.1

dev_dependencies:
  test: ^0.12.10

environment:
  sdk: '>=1.19.0 <2.0.0'
